language: python
python:
  - "3.6"
install:
  - pip install -e .
env:
  - FLASK_APP=polimipride
script:
  - flask freeze -d "$(pwd)/build"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  fqdn: polimipride.it
  on:
    branch: production